### get waiting-token
### error: no Authorization
GET http://localhost:8082/waiting-token/concerts/4

### get waiting-token
GET http://localhost:8082/waiting-token/concerts/4
Authorization:Bearer eyJraWQiOiJhZWE3MmM1Yi00OTZkLTQ3NmEtYTc5OC0zZDg4NjJkMjlhMTkiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXVkIjoidXNlci1zZXJ2aWNlIiwibmJmIjoxNzU3ODM1NzEyLCJzY29wZSI6WyJwcm9maWxlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4NCIsImV4cCI6MTc1NzgzNjAxMiwiaWF0IjoxNzU3ODM1NzEyLCJqdGkiOiIyYWJlOTUwMi0zZWVkLTRlYjktOGJkYS1iZjNhMGZmOGRkMTYifQ.L_KsooOm34x3WNOGB2ozFa0aT_8NKggOOJrB5NzORK-JbwOFNTGCtRROaRSvJYNwD4YiR14NjUDfUNM4jhiGSAgO0x_lKzZlLjlgWj9IEZXyMwK5_xup4A05WoNm4UHtO9POBfBOYOYulvIkq0APDR61NCeD8w2yahdqXoZSscNahSjJtGycwndsUAlZDshkQK5MURaz1a4EoL3_Yg7qy_wxDLTJdCR0AaTRmuKi-R-jr27-zzt6OUgqepRTUSQCDWhM9cdl1x3ez6WGtO4JAzG4HT2h3KJTjzGrwOHmzOyrfZ_lbMKrCPviYzJ5zvuPGL_ZJLEgGRe4MAmae9jLuw

### get my position
GET http://localhost:8082/waiting-token/concerts/4/position/
