server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing_user
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  client:
    auth:
      domain: localhost
      uri: http://localhost:8084
      authorize_path: /oauth2/authorize
      response_type: code
      client_id: user-service
      client_secret: secret
      grant_type: authorization_code
      redirect_uri: http://localhost:8081/users/login
      scope: profile,openid

logging:
  level:
    com.example.userservice.external.auth.AuthClient: DEBUG
    feign: DEBUG
    org.springframework.security.web.FilterChainProxy: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
