tempo:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "0.0.0.0:4317"
        http:
          endpoint: "0.0.0.0:4318"

service:
  type: ClusterIP

persistence:
  enabled: false

tempoQuery:
  enabled: false