adminUser: admin

adminPassword: admin1234

service:
  type: ClusterIP

persistence:
  enabled: true
  size: 5Gi

initChownData:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
        isDefault: true
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.observability.svc.cluster.local:3200
      - name: Loki
        type: loki
        access: proxy
        url: http://loki.observability.svc.cluster.local:3100

grafana.ini:
  server:
    domain: grafana.local
    root_url: http://grafana.local
    http_port: 3000

  users:
    allow_sign_up: false

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - grafana.local
  path: /
  pathType: Prefix