apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  SERVER_PORT: "8081"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ticketing_user"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  EXTERNAL_CLIENT_AUTH_DOMAIN: "ticketing.com"
  EXTERNAL_CLIENT_AUTH_USER_URI: "http://auth.ticketing.com"
  EXTERNAL_CLIENT_AUTH_SERVER_URI: "http://auth-service:8084"
  EXTERNAL_CLIENT_AUTH_REDIRECT_URI: "http://user.ticketing.com/users/login"
