server:
  port: 8083
  ssl:
    enabled: true
    key-store: classpath:backend.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-alias: springboot

spring:
  profiles:
    include:
      - resource
  data:
    redis:
      host: 127.0.0.1
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/ticketing_reservation
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

external:
  client:
    concert:
      url: http://localhost:8080
    concert-seat:
      url: http://localhost:8080
    payment:
      url: http://localhost:8085