server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing_payment
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

PSP:
  toss:
    secretKey: test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
    url: https://api.tosspayments.com