apiVersion: v1
kind: ConfigMap
metadata:
  name: concert-service-config
data:
  SERVER_PORT: "8080"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/ticketing_concert"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "root"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4317"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"