apiVersion: v1
kind: ConfigMap
metadata:
  name: waiting-service-config
data:
  SERVER_PORT: "8082"
  SPRING_DATA_REDIS_HOST: "redis-service"
  SPRING_DATA_REDIS_PORT: "6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo.observability.svc.cluster.local:4317"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"